// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers(in *jlexer.Lexer, out *OrderDTOSlice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(OrderDTOSlice, 0, 1)
			} else {
				*out = OrderDTOSlice{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 OrderDTO
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers(out *jwriter.Writer, in OrderDTOSlice) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v OrderDTOSlice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderDTOSlice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderDTOSlice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderDTOSlice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers(l, v)
}
func easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers1(in *jlexer.Lexer, out *OrderDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "number":
			out.OrderID = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "accrual":
			if in.IsNull() {
				in.Skip()
				out.Accrual = nil
			} else {
				if out.Accrual == nil {
					out.Accrual = new(float64)
				}
				*out.Accrual = float64(in.Float64())
			}
		case "uploaded_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UploadedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers1(out *jwriter.Writer, in OrderDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Accrual != nil {
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Accrual))
	}
	{
		const prefix string = ",\"uploaded_at\":"
		out.RawString(prefix)
		out.Raw((in.UploadedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB00e796eEncodeGithubComUjweghGophermartInternalAppHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB00e796eDecodeGithubComUjweghGophermartInternalAppHandlers1(l, v)
}
