// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers(in *jlexer.Lexer, out *UserRegisterDto) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers(out *jwriter.Writer, in UserRegisterDto) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserRegisterDto) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserRegisterDto) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserRegisterDto) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserRegisterDto) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers(l, v)
}
func easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers1(in *jlexer.Lexer, out *UserLoginDto) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers1(out *jwriter.Writer, in UserLoginDto) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserLoginDto) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserLoginDto) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2b7a6f05EncodeGithubComUjweghGophermartInternalAppHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserLoginDto) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserLoginDto) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2b7a6f05DecodeGithubComUjweghGophermartInternalAppHandlers1(l, v)
}
